# Generated by Django 3.2.8 on 2021-12-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0006_alter_funcionario_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='idade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
