# Generated by Django 3.2.8 on 2021-10-16 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departamentos',
            new_name='Departamento',
        ),
    ]
